/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleAlertsRouteImport } from './routes/_console.alerts'
import { Route as ConsoleOverviewRouteImport } from './routes/_console.overview'
import { Route as ConsoleResultRouteImport } from './routes/_console.result'
import { Route as ConsoleWorkspaceRouteImport } from './routes/_console.workspace'
import { Route as ConsoleCaseCaseIdRouteImport } from './routes/_console.case.$caseId'
import { Route as ConsoleInvestigationCaseIdRouteImport } from './routes/_console.investigation.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAlertsRoute = ConsoleAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOverviewRoute = ConsoleOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleResultRoute = ConsoleResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWorkspaceRoute = ConsoleWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCaseCaseIdRoute = ConsoleCaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleInvestigationCaseIdRoute =
  ConsoleInvestigationCaseIdRouteImport.update({
    id: '/investigation/$caseId',
    path: '/investigation/$caseId',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof ConsoleAlertsRoute
  '/overview': typeof ConsoleOverviewRoute
  '/result': typeof ConsoleResultRoute
  '/workspace': typeof ConsoleWorkspaceRoute
  '/case/$caseId': typeof ConsoleCaseCaseIdRoute
  '/investigation/$caseId': typeof ConsoleInvestigationCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof ConsoleAlertsRoute
  '/overview': typeof ConsoleOverviewRoute
  '/result': typeof ConsoleResultRoute
  '/workspace': typeof ConsoleWorkspaceRoute
  '/case/$caseId': typeof ConsoleCaseCaseIdRoute
  '/investigation/$caseId': typeof ConsoleInvestigationCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/alerts': typeof ConsoleAlertsRoute
  '/_console/overview': typeof ConsoleOverviewRoute
  '/_console/result': typeof ConsoleResultRoute
  '/_console/workspace': typeof ConsoleWorkspaceRoute
  '/_console/case/$caseId': typeof ConsoleCaseCaseIdRoute
  '/_console/investigation/$caseId': typeof ConsoleInvestigationCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/overview'
    | '/result'
    | '/workspace'
    | '/case/$caseId'
    | '/investigation/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/overview'
    | '/result'
    | '/workspace'
    | '/case/$caseId'
    | '/investigation/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/_console/alerts'
    | '/_console/overview'
    | '/_console/result'
    | '/_console/workspace'
    | '/_console/case/$caseId'
    | '/_console/investigation/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/alerts': {
      id: '/_console/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ConsoleAlertsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/overview': {
      id: '/_console/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ConsoleOverviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/result': {
      id: '/_console/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ConsoleResultRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/workspace': {
      id: '/_console/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof ConsoleWorkspaceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/case/$caseId': {
      id: '/_console/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof ConsoleCaseCaseIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/investigation/$caseId': {
      id: '/_console/investigation/$caseId'
      path: '/investigation/$caseId'
      fullPath: '/investigation/$caseId'
      preLoaderRoute: typeof ConsoleInvestigationCaseIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAlertsRoute: typeof ConsoleAlertsRoute
  ConsoleOverviewRoute: typeof ConsoleOverviewRoute
  ConsoleResultRoute: typeof ConsoleResultRoute
  ConsoleWorkspaceRoute: typeof ConsoleWorkspaceRoute
  ConsoleCaseCaseIdRoute: typeof ConsoleCaseCaseIdRoute
  ConsoleInvestigationCaseIdRoute: typeof ConsoleInvestigationCaseIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAlertsRoute: ConsoleAlertsRoute,
  ConsoleOverviewRoute: ConsoleOverviewRoute,
  ConsoleResultRoute: ConsoleResultRoute,
  ConsoleWorkspaceRoute: ConsoleWorkspaceRoute,
  ConsoleCaseCaseIdRoute: ConsoleCaseCaseIdRoute,
  ConsoleInvestigationCaseIdRoute: ConsoleInvestigationCaseIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
